// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:fgtagro_mobile/models/cache/cache_record.dart';
import 'package:fgtagro_mobile/models/cart.dart';
import 'package:fgtagro_mobile/models/cartitems.dart';
import 'package:fgtagro_mobile/models/category.dart';
import 'package:fgtagro_mobile/models/conversation.dart';
import 'package:fgtagro_mobile/models/device_info.dart';
import 'package:fgtagro_mobile/models/message.dart';
import 'package:fgtagro_mobile/models/order.dart';
import 'package:fgtagro_mobile/models/product.dart';
import 'package:fgtagro_mobile/models/seller.dart';
import 'package:fgtagro_mobile/models/user.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CacheRecordAdapter());
    registerAdapter(CartAdapter());
    registerAdapter(CartGroupAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ConversationModelAdapter());
    registerAdapter(CustomDevInfoAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(MessageRoleAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(OrderStatusAdapter());
    registerAdapter(ProductCategoryModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductSellerModelAdapter());
    registerAdapter(SellerProfileModelAdapter());
    registerAdapter(StoreModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CacheRecordAdapter());
    registerAdapter(CartAdapter());
    registerAdapter(CartGroupAdapter());
    registerAdapter(CartItemAdapter());
    registerAdapter(CategoryModelAdapter());
    registerAdapter(ConversationModelAdapter());
    registerAdapter(CustomDevInfoAdapter());
    registerAdapter(MessageModelAdapter());
    registerAdapter(MessageRoleAdapter());
    registerAdapter(MessageTypeAdapter());
    registerAdapter(OrderModelAdapter());
    registerAdapter(OrderStatusAdapter());
    registerAdapter(ProductCategoryModelAdapter());
    registerAdapter(ProductModelAdapter());
    registerAdapter(ProductSellerModelAdapter());
    registerAdapter(SellerProfileModelAdapter());
    registerAdapter(StoreModelAdapter());
    registerAdapter(UserModelAdapter());
    registerAdapter(UserRoleAdapter());
  }
}
